variables:
  - group: demo-vars

jobs:
  - job: API
    displayName: API test and build
    variables:
      IMAGE_NAME: nick96/demo-api
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: ./gradlew test --no-daemon
        displayName: Test API
        workingDirectory: api/
      - script: ./gradlew jibDockerBuild --image=$(IMAGE_NAME) --no-daemon
        displayName: Build API docker image
        workingDirectory: api/
      - script: docker tag $(IMAGE_NAME):latest $(IMAGE_NAME):$(Build.SourceVersion)
        displayName: Tag image
      - task: Docker@2
        displayName: Log into docker hub
        inputs:
          command: login
          containerRegistry: nick96-docker-hub
      - task: Docker@2
        displayName: Push API docker image to container registry
        inputs:
          command: push
          containerRegistry: nick96-docker-hub
          repository: $(IMAGE_NAME)
          tags: |
           $(Build.SourceVersion)
           latest
      - task: InstallSSHKey@0
        displayName: Install SSH key
        inputs:
          knownHostsEntry: 
          sshPublicKey: |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCUzGXF8XvvfRxaq4wf+vj0OjE7i22Ci4H+Je29Ri2ChNEVQMrNk70K/GiCRkOQL5JmHwVNh/Z0qFUBdhyJDBwrqtTD/KqujKszFil1/gJgr+Fl743RUVU1JR5PpW3/TXJ5Zys4CFCNRBqPHJUym+EYXI/C4ODg0ce3vGSw353p137orKRlsXlPtVGtb28gFtjEH5mOHzPBR8O8FbA9DvrGcETa2wt+awyzdZeCyiMzN7OHHC8IHjNi5gk3qke5yZLlH7SkgrE180mjGQ3Yx0yAjC1TnFC3ZEv93EFWhqGdlMt2rQaN6MPSWEvMeMPlEmAv/yrachI3SiNdIh+aRRsdy6sDoHwX+NukRQQirMatByxk4OuequmQlRe18+FCSNsBlWcswCgznBw6p3pEYFlGMqFYMpVfJ7Byfiev4/JfXmATWhuQhXUP75TMMnhZ7OTD5fiDdppAA4Ndo784jgPYbyZB5Garulz1b25DZYS0xHiBUUieDmmbG2GQefsEbis= nspain@raptor
          sshKeySecureFile: azure_id_rsa
      - script: |
              ansible-playbook -v playbook.yml \
                 -vvvv \
                 -i hosts \
                 -u root \
                 --extra-vars "api_image=$(IMAGE_NAME):$(Build.SourceVersion) email=$(EMAIL) ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
        displayName: Ansible deployment
        workingDirectory: 'api/playbook'

  - job: Frontend
    displayName: Frontend test and build
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: yarn install && CI=1 yarn test
        displayName: Test frontend
        workingDirectory: frontend
      - script: yarn build
        displayName: Build frontend
        workingDirectory: frontend
      - script: sudo npm install -g firebase-tools
        displayName: Install firebase CLI
      - script: sudo firebase deploy --token=$(FIREBASE_TOKEN) --project $(FIREBASE_PROJECT)
        workingDirectory: frontend
        displayName: Firebase deploy