variables:
  API_IMAGE_NAME: demo-api

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: ./gradlew clean test
  workingDirectory: api/
  displayName: Test API

- script: ./gradlew jibDockerBuild --image=$(API_IMAGE_NAME)
  workingDirectory: api/
  displayName: Build API docker image

- script: docker save $(API_IMAGE_NAME) | gzip > $(API_IMAGE_NAME).tar.gz
  displayName: Archive docker image

- script: yarn install
  workingDirectory: frontend/
  displayName: Install frontend dependencies

- script: CI=true yarn test
  workingDirectory: frontend/
  displayName: Test frontend

- script: yarn build
  workingDirectory: frontend/
  displayName: Build frontend

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: frontend
    PathtoPublish: frontend/build
